a = """URL_ID,	URL,	POSITIVE SCORE	,NEGATIVE SCORE	,POLARITY SCORE	,SUBJECTIVITY SCORE	,AVG SENTENCE LENGTH	,PERCENTAGE OF COMPLEX WORDS,	FOG INDEX,	AVG NUMBER OF WORDS PER SENTENCE,	COMPLEX WORD COUNT	,WORD COUNT	,SYLLABLE PER WORD,	PERSONAL PRONOUNS	,AVG WORD LENGTH"""

# a = a.split(",")
# for i in range(len(a)):
#     a[i] = a[i].strip()
# print(a)
# print(len(a))
fields = [
    'URL_ID', 'URL', 'POSITIVE SCORE', 'NEGATIVE SCORE', 'POLARITY SCORE', 'SUBJECTIVITY SCORE', 'AVG SENTENCE LENGTH', 'PERCENTAGE OF COMPLEX WORDS', 'FOG INDEX', 'AVG NUMBER OF WORDS PER SENTENCE', 'COMPLEX WORD COUNT', 'WORD COUNT', 'SYLLABLE PER WORD', 'PERSONAL PRONOUNS', 'AVG WORD LENGTH'
]
